# Generated by Django 4.2.4 on 2023-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_messages_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
