# Generated by Django 4.2.4 on 2023-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
